name: python tests
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    name: Python ${{ matrix.python-version }} test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: pip
          cache-dependency-path: constraints.txt
      - run: python -m pip install -U pip setuptools
      - run: pip install .[dev,testing] -c constraints.txt
      - run: black --check --diff typedargs
      - run: mypy typedargs
      - run: pytest --cov=typedargs --cov-report=term-missing